print('Введите первое число для прибавления:')
first = input()
print('Введите второе число для прибавления:')
second = input()
print('Введите третье число для прибавления:')
third = input()
print('Сумма равна ' + first + second + third)
